version: '1.0'
services:
  backend:
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - spring-postgres

  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD='password'
    ports:
      - 3306:3306
    networks:
      - spring-postgres


networks:
  spring-postgres:
