version: '3.9'

services:
  springapi:
    container_name: springapi
    image: springapi
    build: ./spring_backend
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:postgresql://postgresdb:5432/recipe_db",
        "spring.datasource.username" : "postgres",
        "spring.datasource.password" : "postgres",
        "spring.jpa.hibernate.ddl-auto" : "none"
        }'
    ports:
      - "8080:8080"
    depends_on:
      - postgresdb
    restart: on-failure:10
    
  postgresdb:
    container_name: postgresdb
    image: postgres:alpine3.17
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      # NOTE: POSTGRES_DB/USER/PASSWORD should match values in app container
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: recipe_db
  
  foodblueprints-fe:
    container_name: foodblueprints-fe
    build: ./foodblueprints-fe
    depends_on:
      - postgresdb
      - springapi
    ports:
    - "3000:3000"
    restart: always